[workspace]
members = [ "daemon", "gg_query", "normalized_data", "provider", "query_interface", "reporting/reporter_cli", "reporting/reporter_state"]
resolver = "2"

[profile.release]
opt-level = 3
incremental = true
lto = "fat"
codegen-units = 1
