[package]
name = "reporter_state"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
hex = "0.4.3"
normalized_data = { path = "../../normalized_data" }
parking_lot = "0.12.3"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["sync"] }
